{
    "window.zoomLevel": -1,
    "editor.fontFamily": "'Monoid', Fira Code",
    "editor.fontLigatures": true,
    "editor.fontSize": 12,
    "editor.lineHeight": 22,
    "terminal.integrated.fontFamily": "'SourceCodePro+Powerline+Awesome Regular', Menlo, 'DejaVu Sans Mono', 'Lucida Console', monospace",
    "vsicons.projectDetection.autoReload": true,
    "typescript.check.tscVersion": false,
    "editor.formatOnSave": true,
    "editor.formatOnType": false,
    "editor.formatOnPaste": false,
    "prettier.singleQuote": true,
    "prettier.trailingComma": "all",
    "prettier.bracketSpacing": true,
    "prettier.printWidth": 120,
    "workbench.sideBar.location": "right",
    "workbench.iconTheme": "vscode-icons",
    "workbench.colorTheme": "OceanDeep",
    "vsicons.dontShowNewVersionMessage": true,
    "javascript.validate.enable": false
}
