{
  "window.zoomLevel": 0,
  "editor.fontFamily": "'Monoid', Fira Code",
  "editor.fontLigatures": true,
  "editor.fontSize": 12,
  "editor.lineNumbers": "on",
  "editor.lineHeight": 22,
  "vsicons.projectDetection.autoReload": true,
  "editor.formatOnSave": true,
  "editor.scrollBeyondLastLine": true,
  "editor.formatOnType": false,
  "editor.formatOnPaste": false,
  "prettier.singleQuote": true,
  "prettier.trailingComma": "all",
  "prettier.bracketSpacing": true,
  "prettier.printWidth": 100,
  "prettier.tabWidth": 2,
  "workbench.sideBar.location": "right",
  "workbench.iconTheme": "vscode-icons",
  "vsicons.dontShowNewVersionMessage": true,
  "javascript.validate.enable": false,
  "workbench.statusBar.visible": false,
  "typescript.check.npmIsInstalled": false,
  "editor.quickSuggestionsDelay": 10,
  "editor.suggestFontSize": 9,
  "editor.cursorBlinking": "expand",
  "editor.cursorStyle": "line-thin",
  "editor.renderIndentGuides": true,
  "editor.minimap.enabled": false,
  "editor.tabSize": 2,
  "editor.snippetSuggestions": "top",
  "sync.gist": "d3c2071e4e848ad210f4ac75f73694d0",
  "sync.lastUpload": "2017-09-11T23:14:23.338Z",
  "sync.autoDownload": false,
  "sync.autoUpload": false,
  "sync.lastDownload": "2017-09-12T21:51:21.426Z",
  "sync.forceDownload": false,
  "sync.anonymousGist": false,
  "sync.host": "",
  "sync.pathPrefix": "",
  "sync.quietSync": false,
  "sync.askGistName": false,
  "terminal.integrated.fontFamily": "'Source Code Pro for Powerline'",
  "terminal.integrated.setLocaleVariables": false,
  "terminal.integrated.fontLigatures": true,
  "terminal.integrated.fontSize": 10,
  "workbench.colorTheme": "Cobalt2"
}
